# Generated by Django 3.0 on 2021-01-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0003_auto_20210129_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
