# Generated by Django 3.0 on 2021-01-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0005_auto_20210130_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='trainers',
        ),
        migrations.AddField(
            model_name='researcher',
            name='trainers',
            field=models.ManyToManyField(related_name='trainers', to='pokes.Trainer'),
        ),
    ]
